apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: contacts.g9h.io
spec:
  group: g9h.io
  scope: Namespaced
  names:
    plural: contacts
    singular: contact
    kind: Contact
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              Name:
                type: string
              Surname:
                type: string
              Email:
                type: string
              Telephone:
                type: string
              Mobile:
                type: string
              Company:
                type: string
              Department:
                type: string
              Address:
                type: string
              Keywords:
                type: array
                items:
                  type: string
              Notes:
                type: string
    additionalPrinterColumns:
    - jsonPath: .spec.Name
      name: firstName
      type: string
    - jsonPath: .spec.Surname
      name: Surname
      type: string
    - jsonPath: .spec.Email
      name: Email
      type: string
    - jsonPath: .spec.Mobile
      name: Mobile
      type: string
    - jsonPath: .spec.Keywords
      name: Keywords
      type: string